# Package setup

The DESCRIPTION file is created using this code.

```{r package-setup, message=FALSE, results='hide'}
usethis::create_package(
  path = ".",
  fields = list(
    Package = params$package_name,
    Version = "0.0.0.9000",
    Title = "flowtrend",
    Description = "Time-smooth mixture modeling for flow cytometry data.",
    `Authors@R` = person(
      given = "Sangwon",
      family = "Hyun",
      email = "sangwonh@ucsc.edu",
      role = c("aut", "cre")
      )
  )
)
usethis::use_mit_license(copyright_holder = "Sangwon Hyun")
```

The following is what will show up when someone types `package?flowtrend` in
the console.

```{package_doc}
#' flowtrend
#'
#' This package implements the `flowtrend` method for automatic gating of flow cytometry data using trend filtering.
#' 
#' @docType package
```


This package will have some dependancies:

```{r dependencies, message = FALSE}
library(tidyverse)
library(ggplot2)
usethis::use_package("tidyverse", type = "depends") 
usethis::use_package("ggplot2")
usethis::use_package("clue")
usethis::use_package("glmnet")
```

