#+title: This is some debugging because litr::render doesn't work

* I fixed it!!

** The problem was:

Inadvertently I found a problem:
https://stackoverflow.com/questions/58610155/problem-installing-r-package-ld-warning-directory-not-found-for-option

which leads me to:
https://thecoatlessprofessor.com/programming/cpp/r-compiler-tools-for-rcpp-on-macos/

Where I can't run
~Rcpp::sourceCpp('path/to/file/helloworld.cpp')~
~Rcpp::sourceCpp('~/repos/flowtrend/helloworld.cpp')~

without running into the error

#+begin_src > Rcpp::sourceCpp('helloworld.cpp')
using C++ compiler: ‘Apple clang version 14.0.3 (clang-1403.0.22.14.1)’
using SDK: ‘MacOSX13.3.sdk’
clang++ -arch arm64 -std=gnu++17 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I../inst/include   -I"/Users/sangwonh/R/libs/Rcpp/include" -I"/Users/sangwonh/R/libs/RcppArmadillo/include" -I"/Users/sangwonh/repos/flowtrend" -I/opt/R/arm64/include    -fPIC  -falign-functions=64 -Wall -g -O2  -c helloworld.cpp -o helloworld.o
clang++ -arch arm64 -std=gnu++17 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/opt/R/arm64/lib -o sourceCpp_2.so helloworld.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/opt/gfortran/lib/gcc/aarch64-apple-darwin20.0/12.2.0 -L/opt/gfortran/lib -lgfortran -lemutls_w -lquadmath -llapack -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
ld: warning: directory not found for option '-L/opt/gfortran/lib/gcc/aarch64-apple-darwin20.0/12.2.0'
ld: warning: directory not found for option '-L/opt/gfortran/lib'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [sourceCpp_2.so] Error 1
Error in Rcpp::sourceCpp("helloworld.cpp") : 
  Error 1 occurred building shared library.

WARNING: The tools required to build C++ code for R were not found.

Please install Command Line Tools for XCode (or equivalent).
#+end_src

How do you fix this? It seems like fortran can't be found.

** The solution was this:

This definitively fixed it:
https://stackoverflow.com/questions/29992066/rcpp-warning-directory-not-found-for-option-l-usr-local-cellar-gfortran-4-8/29993906#29993906
where I added this:
~FLIBS = -L`gfortran -print-file-name=libgfortran.dylib | xargs dirname`~
to my ~.R/Makevars~ file.

Also useful: section 2.16.2 of
https://dirk.eddelbuettel.com/code/rcpp/Rcpp-FAQ.pdf
and 
https://stackoverflow.com/a/39202503
which suggests to modify the ~FLIBS~ variable.


* Old notes

One can run this command:

~R CMD config CXX~

and get  ~clang++ -arch arm64 -std=gnu++17~

which makes me confused about the error message.

#+begin_src 
23 warnings generated.
clang++ -arch arm64 -std=gnu++17 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/opt/R/arm64/lib -o sourceCpp_2.so filefb277908921f.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/opt/gfortran/lib/gcc/aarch64-apple-darwin20.0/12.2.0 -L/opt/gfortran/lib -lgfortran -lemutls_w -lquadmath -llapack -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
ld: warning: directory not found for option '-L/opt/gfortran/lib/gcc/aarch64-apple-darwin20.0/12.2.0'
ld: warning: directory not found for option '-L/opt/gfortran/lib'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [sourceCpp_2.so] Error 1

Quitting from lines 2231-2293 [sylvester-solver-rcpp] (_main.Rmd)
Error:
! Error 1 occurred building shared library.
Backtrace:
  1. base::withCallingHandlers(...)
  2. bookdown (local) fun(...)
  3. bookdown:::render_cur_session(...)
  4. rmarkdown::render(main, output_format, ..., clean = clean, envir = envir)
  5. knitr::knit(knit_input, knit_output, envir = envir, quiet = quiet)
     ...
 10. knitr:::process_group.block(group)
 11. knitr:::call_block(x)
 12. knitr:::block_exec(params)
 15. knitr (local) engine(options)
 17. Rcpp (local) `<fn>`(...)
Warning message:
In get_engine(options$engine) :
  Unknown language engine 'C' (must be registered via knit_engines$set()).

WARNING: The tools required to build C++ code for R were not found.

Please install Command Line Tools for XCode (or equivalent).

                                                                                                                                                                          
Execution halted
Error: Failed to run 'with_cleanup(bookdown::render_book, package_dir)' in a new R session.
#+end_src

This command tells you the version of CXX ~R CMD config CXX~.

#+begin_src 
~clang++ -arch arm64 -std=gnu++17~
#+end_src



** Fixing Rcpp


Inadvertently I found a problem:
https://stackoverflow.com/questions/58610155/problem-installing-r-package-ld-warning-directory-not-found-for-option

which leads me to:
https://thecoatlessprofessor.com/programming/cpp/r-compiler-tools-for-rcpp-on-macos/

Where I can't run
~Rcpp::sourceCpp('path/to/file/helloworld.cpp')~
~Rcpp::sourceCpp('~/repos/flowtrend/helloworld.cpp')~

without running into the error

#+begin_src > Rcpp::sourceCpp('helloworld.cpp')
using C++ compiler: ‘Apple clang version 14.0.3 (clang-1403.0.22.14.1)’
using SDK: ‘MacOSX13.3.sdk’
clang++ -arch arm64 -std=gnu++17 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I../inst/include   -I"/Users/sangwonh/R/libs/Rcpp/include" -I"/Users/sangwonh/R/libs/RcppArmadillo/include" -I"/Users/sangwonh/repos/flowtrend" -I/opt/R/arm64/include    -fPIC  -falign-functions=64 -Wall -g -O2  -c helloworld.cpp -o helloworld.o
clang++ -arch arm64 -std=gnu++17 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/opt/R/arm64/lib -o sourceCpp_2.so helloworld.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/opt/gfortran/lib/gcc/aarch64-apple-darwin20.0/12.2.0 -L/opt/gfortran/lib -lgfortran -lemutls_w -lquadmath -llapack -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
ld: warning: directory not found for option '-L/opt/gfortran/lib/gcc/aarch64-apple-darwin20.0/12.2.0'
ld: warning: directory not found for option '-L/opt/gfortran/lib'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [sourceCpp_2.so] Error 1
Error in Rcpp::sourceCpp("helloworld.cpp") : 
  Error 1 occurred building shared library.

WARNING: The tools required to build C++ code for R were not found.

Please install Command Line Tools for XCode (or equivalent).
#+end_src

which is the meat of the problem. Reading it carefully..


It seems that gfortran is missing, but I can't locate seem to fix it.

** gfortran and gcc needs to have same version

https://stackoverflow.com/questions/10881002/lgfortran-not-found

This page seems to indicate that gfortran and gcc need to have same
version. They don't right now.


This could be helpful:

#+begin_src 
(base) sangwonh@Sangwons-MacBook-Air:~$ clang -v
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: arm64-apple-darwin22.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
(base) sangwonh@Sangwons-MacBook-Air:~$ which clang
clang is /usr/bin/clang
#+end_src

(I found this to be helpful as well
https://stackoverflow.com/questions/10881002/lgfortran-not-found)

~which gfortran~
gives
#+begin_src 
gfortran is /opt/homebrew/bin/gfortran
#+end_src


** gfortran isn't detected
https://stackoverflow.com/questions/32977363/gfortran-doesnt-work-after-upgrading-to-el-capitan

** Reinstalling gfortran and gcc
https://wiki.usask.ca/pages/viewpage.action?pageId=1935648493


** Where is R?

R is here:

> system("type R")
/usr/local/bin/R

or actually here:

> R.home()
[1] "/Library/Frameworks/R.framework/Resources/"
> file.path(R.home("bin"), "R")
[1] "/Library/Frameworks/R.framework/Resources/bin/R"
