# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Solve "barebones" sylvester equation that takes upper triangular matrices as coefficients.
#' 
#' @param TA Upper-triangular matrix
#' @param TB Upper-triangular matrix
#' @param C matrix
#' @export
matrix_function_solve_triangular_sylvester_barebonesC2 <- function(TA, TB, C) {
    .Call('_flowtrend_matrix_function_solve_triangular_sylvester_barebonesC2', PACKAGE = 'flowtrend', TA, TB, C)
}

dmvnorm_arma_fast <- function(x, mean, sigma, logd = FALSE) {
    .Call('_flowtrend_dmvnorm_arma_fast', PACKAGE = 'flowtrend', x, mean, sigma, logd)
}

